### ISSUE TITLE
Specific information about this model. 

### ISSUE THREAD

**Issue by midannii** [monologg/KoBigBird#2]
## Checklist

- [ x ] I've searched the project's [`issues`](https://github.com/monologg/KoBigBird/issues?q=is%3Aissue)

## ❓ Question

- You mentioned  "모두의 말뭉치, 한국어 위키, Common Crawl, 뉴스 데이터 등 다양한 데이터로 학습" and I want to know the size of total corpus for pre-training. 

- Also I want to know the vocab size of this model.

**Comment by monologg** [comment]
- We used approximately 70GB for pretraining.
- Vocab size is 32500. Check [config.json](https://huggingface.co/monologg/kobigbird-bert-base/blob/main/config.json) for more details.

**Comment by midannii** [comment]
Thank you :)
