### ISSUE TITLE
Pretraining Epoch 질문

### ISSUE THREAD

**Issue by KimJaehee0725** [monologg/KoBigBird#3]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/monologg/KoBigBird/issues?q=is%3Aissue)

## ❓ Question

안녕하세요 
저는 현재 친구들과 함께 4096 토큰을 입력받아 요약 태스크를 수행할 수 있는 모델을 만들고 있습니다. 
처음엔 빅버드 + 버트 조합으로 해보려고 했는데, 이미 monologg 님께서 만들어주셨더라구요 ㅎㅎ
그래서 롱포머 + 바트 + 페가수스 조합으로 학습을 진행하려 하고 있습니다. 
pretrained된 KoBart를 기반으로 어텐션을  롱포머로 바꾼 후, 페가수스 task를 수행하는 구조로 되어 있습니다. 

현재 13GB의 데이터를 모아서 전처리와 데이터로더 작성, 모델 코드까지는 완료한 상태입니다. 이번 주 내로 학습을 진행하려 하고 있습니다. 

저희가 가진 GPU로는 대략 이틀이면 1 에포크를 돌 수 있을 것 같은데, monologg님께서는 KoBirBird 모델 개발 시 에포크를 얼마나 도셨는지 여쭤보고 싶습니다. 

아무래도 pretrained 된 모델을 가져다 쓰다보니 에포크를 많이 돌 필요는 없을 것 같은데, 기준점으로 삼고 싶어서요!

말이 길어졌는데 요약하자면, KoBirBird 학습 시 에포크를 얼마나 주셨는지 궁금합니다. 또한, 그 기준은 무엇으로 삼으셨는지도 궁금합니다.

**Comment by monologg** [comment]
빅버드 + 버트 조합의 요약 모델은 제가 만든 것이 아닌데 착오가 있으신 것 같습니다. 
@KimJaehee0725 님이 하려는 것은 pretraining보다는 finetuning인 것 같은데, 둘의 접근법은 별개로 봐야할 것 같습니다.

KoBigBird pretraining과 관련해서는, epoch의 경우는 따로 고려하지 않고 최대한 많은 step을 돌리려 했습니다. 
BERT pretrained 모델에서 warm start를 했어도, 새로운 attention과 새로운 아키텍쳐가 사용되었기에 추가적인 학습이 많이 필요했고,
pretraining을 오래할수록 subtask에서 성능 향상을 보였습니다.

**Comment by KimJaehee0725** [comment]
안녕하세요 
https://github.com/monologg/KoBigBird/blob/master/pretrain/README.md
위 링크에서 BERT로 WARM START를 하셨다고 해서 BERT를 학습시키고 이를 다시 BIGBIRD에 활용하신 것으로 이해했습니다! 물론 KoBirBird가 요약 모델은 아니지만 기존의 한국어 pretrain 모델을 이용해 긴 시퀀스(4096)을 입력으로 하는 모델을 개발하셔서 개발 과정을 자세히 알면 도움이 될까 하여 여쭤봤습니다! 

말씀해주신 대로 최대한 step을 돌리는 것이 KoBigBird 성능에는 도움이 되었다면 저희도 그렇지 않을까 합니다. 

도움 감사드립니다!!
